import fs from "node:fs";
import opentype from "opentype.js";
import CFB from "cfb";
import JSZip from "jszip";
import * as lib from "pdf-lib";
import { TextEngine } from "../../web/js/core/text.js";
import { buildSet } from "../../web/js/core/tplbuild.js";
import { readIoExcel } from "../../web/js/core/io_excel.js";
import { buildPdf } from "../../web/js/core/pdfexport.js";
const W = "C:/Users/Hitesh ingale/Desktop/wasm-build/";
const b = fs.readFileSync("web/fonts/LiberationSans-Regular.ttf");
const engine = new TextEngine(opentype.parse(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength)));
const dir = "source/templates/";
const files = fs.readdirSync(dir).filter((n) => n.endsWith(".dwg")).map((n) => ({ name: n, bytes: new Uint8Array(fs.readFileSync(dir + n)) }));
const set = await buildSet("mega", "mega", files, { engine, CFB, log: () => {} });
const io = await readIoExcel(JSZip, fs.readFileSync("source/1662.MEGA EPC-25004_IO ASSIGNMENT-08-08-2026.xlsx"), "mega.xlsx", set.info);
const golden = JSON.parse(fs.readFileSync(W + "golden2/io.json", "utf8"));
console.log("counts equal:", JSON.stringify(io.counts) === JSON.stringify(golden.counts), "modules", io.modules.length, golden.modules.length, "warnings", io.warnings.length, golden.warnings.length);
let bad = 0;
io.modules.forEach((m, i) => { const g = golden.modules[i]; m.sheets.forEach((sh, j) => { const a = Object.values(sh.texts).sort(), c = Object.values(g.sheets[j].texts).sort(); if (JSON.stringify(a) !== JSON.stringify(c)) { bad++; if (bad < 4) console.log("texts differ", m.module, j, a.filter((x) => !c.includes(x)).slice(0, 4), c.filter((x) => !a.includes(x)).slice(0, 4)); } }); });
console.log("sheets whose texts differ:", bad);
const order = { AI: 0, AO: 1, RTD: 2, DI: 3, DO: 4 };
const mods = [...io.modules].sort((a, b) => (order[a.type] ?? 9) - (order[b.type] ?? 9) || a.index - b.index);
const sheets = []; for (const m of mods) for (const sh of m.sheets) sheets.push({ tid: sh.template, texts: sh.texts, numbering: null });
sheets.forEach((s, i) => (s.numbering = [i + 1, sheets.length]));
fs.writeFileSync(W + "out/mega_all.pdf", await buildPdf(lib, engine, set.info, set.blank, sheets, "mega"));
console.log("pdf sheets", sheets.length);
